# Generated by Django 5.1.6 on 2025-03-01 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='property_photos/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.property'),
        ),
    ]
