# Generated by Django 5.1.6 on 2025-03-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_property_photo_alter_booking_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/property_photos/'),
        ),
    ]
