# Generated by Django 5.1.6 on 2025-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_property_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Booking/media/property_photos/'),
        ),
    ]
