# Generated by Django 5.1.6 on 2025-03-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photo',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='media/property_photos/'),
        ),
    ]
